### ISSUE TITLE
Show table membership prices even if select box is greyed out

### ISSUE THREAD

**Issue by Davorak** [chriscauley/txrx.org#70]
Right now it is not possible to look at the higher table membership options since the select box is disabled.

![image](https://cloud.githubusercontent.com/assets/810921/6771077/2fbbc582-d0a2-11e4-98a5-3ec36b5801bf.png)

**Comment by chriscauley** [comment]
That's by design. Because we have no takes available people need to ask
first. This has always been the case but three months ago people started
signing up without asking which meant we lost money refunding their
purchase, so I disabled it. Did some one try to sign up?

**Comment by chriscauley** [comment]
After some time to think about this (6 months) I opted to grey out the button and alert the user when they click on it. The select is still accessible.

https://txrxlabs.org/join-us/
